### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by casdr** [jayfk/statuspage#10]
Currently, systems aren't being sorted. It would be nice if they would be sorted alphabetically.

![image](https://cloud.githubusercontent.com/assets/7041290/13602688/6dbded00-e538-11e5-9d74-e739b4d3085d.png)

**Comment by brianjking** [comment]
+1 

Better yet, if we could configure the order of sorting.

**Comment by jayfk** [comment]
Done in https://github.com/jayfk/statuspage/commit/4a8ee626adcc6967e4c16cf5164c1c3e57f0ed53
