### ISSUE TITLE
Don't update when nothing changes

### ISSUE THREAD

**Issue by casdr** [jayfk/statuspage#12]
I'm running statuspage update in a cronjob, but the repo keeps being updated even when nothing changed. It would be nice if a check would be built-in to see if something actually changed.

**Comment by casdr** [comment]
Probably #10 is relevant as the update changes the order of the systems. Currently fixed it by setting up a webhook.

**Comment by jayfk** [comment]
Yup, that's definitely needed.

**Comment by jayfk** [comment]
Done in https://github.com/jayfk/statuspage/commit/4a8ee626adcc6967e4c16cf5164c1c3e57f0ed53
