### ISSUE TITLE
unable to create, error is coming

### ISSUE THREAD

**Issue by flik** [jayfk/statuspage#15]
When I run the command, this error was coming:

statuspage create --token=dceb9fa24bf8558d01d34308cffe
-bash: /usr/local/bin/statuspage: cannot execute binary file: Exec format error

then i use the command with sudo
sudo statuspage create --token=dceb9fa24bf8558d01d3430 
/usr/local/bin/statuspage: 1: /usr/local/bin/statuspage: Syntax error: "(" unexpected

**Comment by jayfk** [comment]
What is `uname -a` telling you?

**Comment by flik** [comment]
Linux ubuntu-1gb 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:28:32 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by jayfk** [comment]
No luck then, the binary is for 64bit machines only.

What you could do:

    rm /usr/local/bin/statuspage
    git clone https://github.com/pyupio/statuspage.git
    cd statuspage
    pip install -r requirements/base.txt

This will remove the old binary, clone the project and install all dependencies.

I'm closing this issue in favor of https://github.com/pyupio/statuspage/issues/16

**Comment by flik** [comment]
Now I am getting this error.

statuspage: command not found

**Comment by jayfk** [comment]
There's now a pip-installable package available.

First, remove the old binary:

    rm /usr/local/bin/statuspage

And then, install it with:

    pip install statuspage
