### ISSUE TITLE
StatusPage system function not working!

### ISSUE THREAD

**Issue by IvanLau-NitroHosting** [jayfk/statuspage#198]
The add_system/remove_system and also the config.json is not working! For those two commands, the terminal said Error: `No such command "add_system"` or `Error: No such command "remove_system"`. Also whenever I did a command, it always says `Failed to execute script statuspage`.

I need help, please!

**Comment by HKproMinecraft** [comment]
Also how can we mark a service as operational? Closing the issue on github is not working for me.
