### ISSUE TITLE
Allow better translations

### ISSUE THREAD

**Issue by Art4** [jayfk/statuspage#28]
I've tried to translate the status page and find this issues:

- The word `operational` is hard-coded. It would be nice if it would be in the `template.html`.
- Renaming tags has no impact

It would be nice if this would be possible. Unfortunately I know too little about python.

**Comment by jayfk** [comment]
Before thinking about translations I'd like to sort out #5.

This might sound totally unrelated at first, but whatever comes out of this we might need to rewrite the whole template and ditch `jinja` in favor of some javascript template engine.
