### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jnehlmeier** [jayfk/statuspage#304]
Since you can not create a new statuspage repository out of the box and corresponding pull requests don't seem to be merged, I am wondering if this project is still maintained?

**Comment by jnehlmeier** [comment]
No response in 14 days. Switched to instatus.com which is free (unlimited subscribers and teams!) unless you want your own domain.

**Comment by ourhelpdesk** [comment]
Yeah looks abandoned.   
Instatus.com may look pretty, but is a different thing (it's a monitoring system, not a status system. Difference is that it does not allow to make comments about downtime, planned or not, projected time to completion etc).

**Comment by jnehlmeier** [comment]
@ourhelpdesk Well actually you can use it's API to create automated incidents or you manually create/update incidents with a status (analyzing, solved, ...) and a description text. So you will have a timeline of the concrete incident and a history of all incidents. 

An "incident" can also be something like a planned downtime. In that case it could be displayed as warning instead of an error (orange vs red). In the description you would tell your customers about the planned/remaining time.

**Comment by chenrui333** [comment]
Do we have any maintained forks at this moment?

**Comment by chenrui333** [comment]
I am gonna help out with the project maintenance, so closing this issue.
