### ISSUE TITLE
Installation for Dummies !

### ISSUE THREAD

**Issue by leovarmak** [jayfk/statuspage#33]
Hey, I am having an issue stating SSL Certificate error.

**Comment by PierreLvx** [comment]
Could you provide more details ?

Does it looks like https://github.com/jayfk/statuspage/issues/6 ?

**Comment by leovarmak** [comment]
@PierreLvx yes I get the same error as in issue #6

**Comment by jakirkham** [comment]
This is an easy fix set the environment variable `SSL_CERT_FILE` to point to your `cert.pem` or similar certificate file. These are not bundled with the binary (nor should they be!).

**Comment by jakirkham** [comment]
Could this be closed as a dup of issue ( https://github.com/jayfk/statuspage/issues/6 ), @jayfk?

**Comment by jayfk** [comment]
👍
