### ISSUE TITLE
Timezone problems?

### ISSUE THREAD

**Issue by MrHalfman** [jayfk/statuspage#42]
Hi, 

I'm French and it seems that when I update my status page with new issues : the issues are not on my server's timezone.

(Seems that the default timezone used is UTC instead of UTC+2).

Thanks,
Halfman.

**Comment by jayfk** [comment]
That's a good catch! I'll make sure to include that with the next release.

**Comment by MrHalfman** [comment]
Thanks for the fast answer :smile:. I will look forward to the next release !

**Comment by jayfk** [comment]
#64 is a small improvement, but ideally I'd like to convert the timestamp to local time.

**Comment by PierreLvx** [comment]
Most likely trivial, using http://momentjs.com/timezone/
