### ISSUE TITLE
pip installable/setup.py?

### ISSUE THREAD

**Issue by jakirkham** [jayfk/statuspage#56]
I'm wondering if there is a reason not to make this `pip`-installable or at least have a `setup.py` file. While I can see this can be installed as a binary and that can have certain advantages, it also presents certain challenges. For instance, what if someone does not want a lighter weight solution, requires building from source, or desires to install this into an existing dev environment (e.g. virtualenv or similar). The current packaging solution makes any of these latter goals challenging if not impossible to solve. Is this a matter of preference, available time, interest, something else and/or combinations of the aforementioned?

**Comment by jayfk** [comment]
> Is this a matter of preference, available time, interest, something else and/or combinations of the aforementioned?

I've found that non python devs have a hard time figuring out what `pip` is and why it's a good idea to create a virtualenv prior to installing packages.

My goal is to make it super easy to use, so I've decided to ship it as a binary.

I would've probably made a `pip` installable package, but one of the dependencies (pygithub) has no release on pypi that supports the file api. The package needs to be pulled from github, but I could'nt find  a way to tell `setup.py` to use it.

**Comment by jakirkham** [comment]
At this point, I'm able to build the binary from source. So, am happy to continue doing it that way personally. Though I figured I'd provide some thoughts on these points.

I can't really provide any suggestions for the first point. Maybe some details or links in the Readme?

As for the last point, that should be doable at least according to this SO [answer]( http://stackoverflow.com/a/29682273 ), but it does feel a bit suboptimal. I suppose vendoring it might be an option. Though some people are opposed to the latter, I think it fits well for your particular use case. Honestly I'd rather see that PR accepted at this point and am not really sure why it hasn't happened yet.

In any event, none of this stops one from still shipping binaries. It just provides another way of getting at a release that is more familiar to the average Python user.

**Comment by jayfk** [comment]
There's now a pip-installable package of statuspage available, see https://github.com/jayfk/statuspage/commit/b8c2f71a0a0c9e42d49b528297e6af818dbfe25d
