### ISSUE TITLE
Support basic Mardown formatting

### ISSUE THREAD

**Issue by PierreLvx** [jayfk/statuspage#59]
It'd be nice and useful to support basic formatting such as bold and italic.

Right now, if these are used in the Github issues, we get raw text on the status page.

**Comment by jayfk** [comment]
Yeah, I like the idea.

**Comment by jayfk** [comment]
Added in https://github.com/jayfk/statuspage/commit/2c51774f2ee77e62f39629958f3c15ca891799d4

**Comment by PierreLvx** [comment]
Awesome, thanks!
