### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [jayfk/statuspage#60]
The first tag here appears to be unusable as one cannot run `statuspage update`. Could we have a new tag that points out a more usable commit?

**Comment by jayfk** [comment]
Commits prior to 87f63cd should be good. However, if you want to create a new page use the pre release here where the `update` command is no longer neccessary (data is synced automatically) https://github.com/jayfk/statuspage/releases/tag/0.3-pre

**Comment by jakirkham** [comment]
So, I tried that but it seems the page never actually loads.

Also, I'm a bit confused as it seems the `update` subcommand reappears in `master` after that release.

**Comment by jakirkham** [comment]
Ok, so I tried to start from commit ( https://github.com/jayfk/statuspage/commit/f5a46d12cd07f86a8f9baaea0f678f71c5a73482 ) and then upgraded to 0.3-pre. That seemed to at least retain the list of services (was unable to create the repo by starting at 0.3-pre 😕). However, it doesn't seem to be autoupdating.

**Comment by jayfk** [comment]
Have you figured that out? There's another thing you could do:

* clone the repo
* install requirements
* run `python statuspage.py [create|update]`

**Comment by jakirkham** [comment]
I mean I got the page generated using the workaround previously mentioned, but it doesn't seem to show the open issue. See this [page]( https://conda-forge.github.io/status/ ) and this issue ( https://github.com/conda-forge/status/issues/1 ). Admittedly I could be doing something totally wrong.

**Comment by jayfk** [comment]
This looks like a bug =/

To be honest, I'd probably stick to the `non automated` version for now. I'm not quite sure if it was a good idea to make it available so early. Using the github api has a couple of benefits but some huge drawbacks.

**Comment by jakirkham** [comment]
> This looks like a bug =/

Ok, as long as I'm not missing something.

> To be honest, I'd probably stick to the `non automated` version for now.

Alright, that's what we will do. If you could tag a good commit (maybe with these changes https://github.com/jayfk/statuspage/pull/52 😉), we will work with that. 

> I'm not quite sure if it was a good idea to make it available so early.

Honestly, it is always a judgement call and this is hard to test. I think it is worthwhile to try out the automated stuff and see how it goes. At least this way you got some (hopefully) useful user feedback. I mean it did say `pre`. It isn't like I wasn't warned. 😄

> Using the github api has a couple of benefits but some huge drawbacks.

Sure. Maybe someone has some good ideas about how best to address this.

**Comment by jayfk** [comment]
New release is out, see https://github.com/jayfk/statuspage/releases/tag/0.3.1 for the binaries, or https://pypi.python.org/pypi/statuspage for the pip package.
