### ISSUE TITLE
Template error when adding template files

### ISSUE THREAD

**Issue by aleccool213** [jayfk/statuspage#68]
*[snip]*

If I need to give more info, please comment

**Comment by jayfk** [comment]
That's probably a packaging problem :(.

You've installed with `pip` right? 

Could you run:

    statuspage --version

**Comment by jayfk** [comment]
I've just created a new release, please update the package with `pip install statuspage==0.3.3` and try again.

If you are still getting the same error, please open this issue again.

**Comment by jayfk** [comment]
You had an access token in your screenshot, I've edited your post and removed it. You should probably get a new one :)

**Comment by aleccool213** [comment]
@jayfk will do. Also thanks for correcting my screw up :)
