### ISSUE TITLE
How to change the names of the labels?

### ISSUE THREAD

**Issue by Th3f** [jayfk/statuspage#83]
I wondered how it is possible to change the names of the issue labels. I wanted to translate my statuspage to another language, but I wasn't able to figure out, how to change the names of the labels "major outage" and "degraded performance". Any clues how to do that?

**Comment by Th3f** [comment]
Maybe one could simply read out the names of the issue-labels, which can be changed very easily... Just as an idea.

**Comment by jayfk** [comment]
Currently, all the strings are hardcoded. To make things worse, the *severity* labels (major outage, degraded perf.., etc.) are also used as css classes. Changing the labels will break basically everything :)

I was thinking of doing the translations on the client side using some kind of javascript library, probably http://i18next.com/.

This makes it extremely easy to add languages and supports language detection out of the box.

**Comment by Th3f** [comment]
That would be an option too. So far it sounds good. :)

**Comment by jayfk** [comment]
Make sure to check out how to upgrade here: https://github.com/jayfk/statuspage#upgrading-from-previous-versions

Since you've heavily edited `template.html`, make a copy somewhere and check out the customizing section: https://github.com/jayfk/statuspage/blob/master/docs/customizing.md
