### ISSUE TITLE
Problems with umlauts

### ISSUE THREAD

**Issue by Th3f** [jayfk/statuspage#90]
Is it possible that the new version of the script doesn't like letters like ä, ö, ü, ß and so on? I noticed further problems when I wanted to use them in issues or e.g. in the config.json.
I also got similar problems using a copyright-character.

Here you can find a screenshot of the error I get everytime when I try to use characters like the ones I mentioned above. Maybe you could help out, @jayfk?
![unbenannt](https://cloud.githubusercontent.com/assets/8012652/18229948/fdffc03c-728c-11e6-8dea-73d058c2d734.png)

**Comment by jayfk** [comment]
Wow, that sucks. I'll check that tomorrow.

**Comment by Th3f** [comment]
Indeed. Maybe this could've something to do with the issue? https://github.com/jayfk/statuspage/blob/master/statuspage/statuspage.py#L472

**Comment by jayfk** [comment]
Fixed in https://github.com/jayfk/statuspage/commit/c6bd06280f760505ea1af9371208d82b8be83a58.

Make sure to run `pip install statuspage --upgrade` and try again.

**Comment by Th3f** [comment]
I did a clean install of the new version.

Am 06.09.2016 14:56 schrieb "Jannis Gebauer" <notifications@github.com>:
