### ISSUE TITLE
Shop link mentioned in the README file is broken.

### ISSUE THREAD

**Issue by machbio** [jayfk/statuspage#94]
Shop link for automating the Status page Updates is broken - https://www.statuspage-backend.com/

**Comment by siddharthlatest** [comment]
@jayfk is this project still maintained?

**Comment by jayfk** [comment]
Yup. The shop was an ongoing cost and nobody was using it, so it took it offline.

**Comment by machbio** [comment]
@jayfk do you know of any other way to automate the status page updates ?

**Comment by siddharthlatest** [comment]
@machbio you can most likely add a travis-ci (or similar) post commit hook.
